--이공계 88기_전혜진--

--1
SELECT EMPNO, ENAME
FROM EMP
WHERE EMPNO = 7369 OR EMPNO = 7698;

--2
SELECT EMPNO, ENAME
FROM EMP
WHERE EMPNO != 7369 AND EMPNO != 7698;

--3
SELECT *
FROM EMP
WHERE SAL >= 3000 AND SAL <= 5000;

--4
SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYYMM') >= '198112';

--5
SELECT MAX(EMPNO)
FROM EMP
WHERE JOB = 'SALESMAN';

--6
SELECT STU_NAME, STU_NO, STU_WEIGHT
FROM STUDENT;

--7
SELECT DISTINCT JOB
FROM EMP;

--8
SELECT ENAME, HIREDATE, SAL
FROM EMP;

--9
SELECT STU_NO, STU_NAME, STU_WEIGHT
FROM STUDENT
WHERE STU_GENDER = 'M' AND STU_DEPT = '컴퓨터정보';

--10
SELECT DISTINCT STU_DEPT
FROM STUDENT
WHERE STU_CLASS = 'C';

--11
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE DEPTNO = 10 OR JOB = 'CLERK';

--12
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE DEPTNO = 10 OR JOB != 'CLERK';

--13
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE ENAME = 'KING' AND DEPTNO = 10 OR JOB != 'CLERK';

--14
SELECT ENAME, JOB, DEPTNO
FROM EMP
WHERE ENAME LIKE 'K%G';

--15
SELECT ENAME, JOB, SAL
FROM EMP
WHERE ENAME LIKE '%T%';

--16
SELECT *
FROM EMP
WHERE MGR IS NOT NULL AND COMM IS NOT NULL;

--17
SELECT *
FROM EMP
WHERE SAL >= 1000
ORDER BY JOB, SAL;

--18
SELECT EMPNO, ENAME, JOB
FROM EMP
WHERE JOB != 'MANAGER' AND JOB IS NOT NULL;

--19
SELECT EMPNO, ENAME, HIREDATE
FROM EMP
WHERE DEPTNO = 30
ORDER BY EMPNO;

--20
SELECT *
FROM EMP
ORDER BY DEPTNO, SAL;