--1
INSERT INTO STUDENT1 (STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_HEIGHT, STU_WEIGHT, STU_GENDER)
VALUES(20101059, '조병준', '컴퓨터정보', 1, 'B', 164, 70, 'M');

--2
INSERT INTO STUDENT1 (STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_GENDER)
VALUES(20102038, '남지선', '전기전자', 1, 'C', 'F');

--3
INSERT INTO STUDENT1 (STU_NO, STU_NAME, STU_DEPT, STU_GRADE, STU_CLASS, STU_GENDER)
VALUES(20103009, '박소신', '기계', (
    SELECT STU_GRADE
    FROM STUDENT1
    WHERE STU_NO = 20153075), (
    SELECT STU_CLASS
    FROM STUDENT1
    WHERE STU_NO = 20153075), 'M');

--4
INSERT INTO STUDENT1
SELECT * 
FROM STUDENT
WHERE STU_GRADE = 3;

--5
UPDATE STUDENT1
SET STU_CLASS = 'B'
WHERE STU_NO = 20131001;

--7
UPDATE STUDENT1
SET STU_GRADE = STU_GRADE + 1;

--8
UPDATE STUDENT1
SET STU_DEPT = '컴퓨터정보', STU_NO = 20141021
WHERE STU_NO = 20142021;

--9
UPDATE ENROL1
SET ENR_GRADE = ENR_GRADE - 10
WHERE SUB_NO = (
    SELECT SUB_NO
    FROM SUBJECT
    WHERE SUB_NAME = '전자회로실험'
);

--10
UPDATE ENROL1
SET ENR_GRADE = 0
WHERE STU_NO = 20151062
AND SUB_NO = (
    SELECT SUB_NO
    FROM SUBJECT
    WHERE SUB_NAME = '소프트웨어공학'
);

--11
DELETE FROM STUDENT1
WHERE STU_NO = 20153088;

--12
INSERT INTO SUBJECT1 (SUB_NO, SUB_NAME, SUB_PROF, SUB_GRADE, SUB_DEPT)
VALUES (112, '자동화시스템', '고종민', 3, '기계');

--13
UPDATE SUBJECT1
SET SUB_NO = 501
WHERE SUB_NO = 110;

--14
DELETE FROM SUBJECT1
WHERE SUB_NO = 101;

--15
UPDATE ENROL1
SET SUB_NO = 999
WHERE SUB_NO NOT IN (
    SELECT SUB_NO
    FROM SUBJECT1
);

--16
UPDATE ENROL1
SET STU_NO = 99999999
WHERE STU_NO NOT IN (
    SELECT STU_NO
    FROM STUDENT1
);

--17
DELETE FROM ENROL1
WHERE SUB_NO = 999;

--18
DELETE FROM ENROL1
WHERE STU_NO = 99999999;

--19
DELETE FROM SUBJECT1
WHERE SUB_NO NOT IN (
    SELECT SUB_NO
    FROM ENROL1
);

--20
DELETE FROM ENROL1;