--SELF JOIN
SELECT A.ENAME, B.ENAME AS 상사
FROM EMP A, EMP B
WHERE A.MGR = B.EMPNO;

--INNER JOIN


--RIGHT OUTER JOIN
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

--LEFT OUTER JOIN
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO
FROM DEPT LEFT OUTER JOIN EMP
ON EMP.DEPTNO = DEPT.DEPTNO;

--동일한 결과
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO
FROM DEPT, EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO(+);

--FULL OUTER JOIN (= LEFT OUTER JOIN + RIGHT OUTER JOIN)

--사원번호, 사원이름과 상사번호, 상사이름을 모두 출력하는 쿼리를 작성하시오
--(단, 사장님도 포함하여 출력할 수 있도록 작성하시오)
SELECT A.EMPNO, A.ENAME, A.MGR, B.ENAME
FROM EMP A LEFT OUTER JOIN EMP B ON A.MGR = B.EMPNO;

--다중 테이블 JOIN 에서는 테이블이 늘어날 수록 속도가 ↓
--로딩이 걸리는 것은 최근에는 통신 속도가 빨라졌기 때문에 대부분 데이터베이스가 원인
