--JOIN
SELECT EMP.ENAME, EMP.JOB, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.JOB = 'MANAGER';

--사원번호, 사원이름, 부서이름, 부서번호를 출력하시오
SELECT E.EMPNO, E.ENAME, D.DNAME, D.DEPTNO
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

--NATURAL JOIN: 이때는 구분자를 넣을 필요가 X
--겹치는 걸 찾아서 하나의 테이블로 표시해줌
--겹치는 게 2개 이상일 경우에는 에러
SELECT EMPNO, ENAME, DNAME, DEPTNO
FROM EMP NATURAL JOIN DEPT;

--JOIN ~ ON
--DEPTNO가 양쪽 모두 있어서 어느쪽 칼럼인지 명시해줘야 함
SELECT EMPNO, ENAME, DNAME, EMP.DEPTNO
FROM EMP JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

--JOIN ~ USING
SELECT EMPNO, ENAME, DNAME, DEPTNO
FROM EMP JOIN DEPT
USING (DEPTNO);

--부서가 30이고, 급여가 1500이상인 사원의 이름, 부서명, 급여를 출력
--WHERE
SELECT E.ENAME, D.DNAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.DEPTNO = 30
AND E.SAL >= 1500;

--NATURAL JOIN
SELECT ENAME, DNAME, SAL
FROM EMP NATURAL JOIN DEPT
WHERE DEPTNO = 30
AND SAL >= 1500;

--JOIN ~ ON
SELECT E.ENAME, D.DNAME, E.SAL
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO = 30
AND E.SAL >= 1500;

--JOIN ~ USING
SELECT ENAME, DNAME, SAL
FROM EMP JOIN DEPT USING (DEPTNO)
WHERE DEPTNO = 30
AND SAL >= 1500;

--사원수가 5명 이상인 부서의 부서명과 사원수를 출력하시오
--WHERE
SELECT DNAME, COUNT(*)
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME
HAVING COUNT(*) >= 5;

--NATURAL JOIN
SELECT DNAME, COUNT(*)
FROM EMP NATURAL JOIN DEPT
GROUP BY DEPT.DNAME
HAVING COUNT(*) >= 5;

--JOIN ~ ON
SELECT DNAME, COUNT(*)
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DNAME
HAVING COUNT(*) >= 5;

--JOIN ~ USING
SELECT DNAME, COUNT(*)
FROM EMP JOIN DEPT USING (DEPTNO)
GROUP BY DEPT.DNAME
HAVING COUNT(*) >= 5;

--각 부서의 이름과 가장 많은 월급의 크기를 출력하시오
--WHERE
SELECT DEPT.DNAME, MAX(EMP.SAL)
FROM DEPT, EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DNAME;

--NATURAL JOIN
SELECT DNAME, MAX(SAL)
FROM DEPT NATURAL JOIN EMP
GROUP BY DNAME;

--JOIN ~ ON
SELECT DEPT.DNAME, MAX(EMP.SAL)
FROM DEPT JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DNAME;

--JOIN ~ USING
SELECT DEPT.DNAME, MAX(EMP.SAL)
FROM DEPT JOIN EMP USING (DEPTNO)
GROUP BY DEPT.DNAME;

--ADAMS 사원이 근무하는 부서이름과 지역이름을 출력
SELECT DNAME, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME = 'ADAMS';

--NEW YORK 이나 DALLAS 지역에 근무하는 사원들의 사원번호, 사원이름을 사원번호 순으로 출력
SELECT EMPNO, ENAME, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE LOC = 'NEW YORK' OR LOC = 'DALLAS'
ORDER BY EMPNO;

--*주의점
--이렇게 적으면 다른 결과가 나온다. 이럴때는 ()로 OR 구문들을 묶거나 JOIN ~ ON 등의 구문으로 구분해 줘야한다
SELECT EMPNO, ENAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND LOC = 'NEW YORK' OR LOC = 'DALLAS'
ORDER BY EMPNO;

--부서이름이 ACCOUNTING 이거나, 지역이름이 CHICAGO 인 사원의 사원번호와 사원이름을 출력
SELECT EMPNO, ENAME, DNAME, LOC
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'ACCOUNTING' OR LOC = 'CHICAGO';